### ISSUE TITLE
Make browser auto-fill login credentials

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/Gramps.js#19]
I find it very annoying that my browsers don't auto-fill username and password on the login page. Should try a workaround like this: https://github.com/home-assistant/frontend/pull/9369

**Comment by brucejackson** [comment]
I read through the link at Home Assistant and the thread that lead to it.  If I understand the proposed solution, it is to create a hidden username/password field.  Since the issue seems to be Password Managers ignoring the ShadowDOM, I would worry they may ignore hidden fields in the future.

It looks like it is possible to create login templates without the shadowDOM -  https://lit-element.polymer-project.org/guide/templates#renderroot

An example found on GitHub of login form using CreateRenderRoot to avoid shadowDOM - https://github.com/dhaven/P1-2021-Ex/blob/343481449637c4efd1b73cbef830e1a57193690d/frontend/src/js/components/login.js  (I haven't tested, I search for login createrenderroot - to find example)

I'm not sure what functionality is lost by doing this...

**Comment by DavidMStraub** [comment]
I think I've succeeded in fixing this, using the Home Assistant trick!
