### ISSUE TITLE
Place title should be taken from name field

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/Gramps.js#21]
See https://github.com/gramps-project/gramps-webapi/issues/190.

**Comment by DavidMStraub** [comment]
@brucejackson it turned out this was easy to fix and indeed just a bug caused by my misunderstanding of place name vs. title. Can you please confirm this is solved for your case using 900e6f2772c60f5c9d1f3dca2009b55e6ea73c1d?

**Comment by brucejackson** [comment]
I think there may be one screen showing title and not name, the list on the main page
![image](https://user-images.githubusercontent.com/1219029/128598082-70f18576-d87e-47e5-84da-79d51d5595f3.png)

Otherwise, it looks great.  I checked Place Details, References, Event Details, Main Event List, Timelines, Map Icons Labels and they all display place names.

**Comment by DavidMStraub** [comment]
Right, good catch! Should be fixed now, too...

**Comment by brucejackson** [comment]
Perfect - that fixed it.  I think this can be closed!
